version: "3.8"

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=blog_db

  db:
    image: mysql:8
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blog_db
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: